apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggapp-deployment
spec:
  selector:
    matchLabels:
      app: bloggapp
  replicas: 2
  template:
    metadata:
      labels:
        app: bloggapp
    spec:
      containers:
        - name: bloggapp
          image: thereddotranch/bloggapp:latest # Updated image to private DockerHub image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred # Reference to the Docker registry secret
---
apiVersion: v1
kind: Service
metadata:
  name: bloggapp-ssvc
spec:
  selector:
    app: bloggapp
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer
